#pragma once

/* Use I2C or Serial, not both */

// #define USE_SERIAL
#define USE_I2C

#define SPLIT_USB_DETECT

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 50

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_MAX_SPEED 3
#define MOUSEKEY_WHEEL_TIME_TO_MAX 255

#define TAPPING_TOGGLE 2

// #define MK_3_SPEED
// #define MK_MOMENTARY_ACCEL

#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(MUSIC_SCALE_SOUND)
#endif

//#define AUDIO_CLICKY

#undef RGBLED_NUM
#define RGBLIGHT_ANIMATIONS
#define RGBLED_NUM 8
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

#define RGBLIGHT_LAYERS
